[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dear_future = "4UHykQD4g6ANrhZXYnKtECq9dq4HxV3JbFCkkRE4krX5"

[programs.devnet]
dear_future = "4UHykQD4g6ANrhZXYnKtECq9dq4HxV3JbFCkkRE4krX5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"